Repository cookierun-tcg-service-developer/CookieBox-Android, pull requests merged in 2023-11, with the labels that each got.

#2 🔀 :: (#1) setting github ci
  .github/workflows/android.yml
  app/build.gradle.kts
  build.gradle.kts
Labels: Setting

#6 🔀 :: (#5) add issue template and pr template
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 3️⃣ Priority: Low, 📄 Type: Docs

#8 🔀 :: (#7) implement gradle convention plugin
  .gitignore
  app/build.gradle.kts
  build-logic/build.gradle.kts
  build-logic/settings.gradle.kts
  build-logic/src/main/java/com/example/cookiebox/ComposeAndroid.kt
  build-logic/src/main/java/com/example/cookiebox/HiltAndroid.kt
  build-logic/src/main/java/com/example/cookiebox/KotlinAndroid.kt
  build-logic/src/main/java/com/example/cookiebox/ProjectExtension.kt
  build-logic/src/main/java/com/example/cookiebox/TestAndroid.kt
  build-logic/src/main/java/cookiebox.android.application.gradle.kts
  build-logic/src/main/java/cookiebox.android.compose.gradle.kts
  build-logic/src/main/java/cookiebox.android.feature.gradle.kts
  build-logic/src/main/java/cookiebox.android.library.gradle.kts
  build-logic/src/main/java/cookiebox.kotlin.library.gradle.kts
  core/data/build.gradle.kts
  core/domain/build.gradle.kts
  core/model/build.gradle.kts
  core/model/src/androidTest/java/com/example/model/ExampleInstrumentedTest.kt
  core/model/src/main/AndroidManifest.xml
  core/model/src/main/java/com/cookiebox/model/.gitkeep
  core/model/src/test/java/com/example/model/ExampleUnitTest.kt
  core/navigation/build.gradle.kts
  core/ui/build.gradle.kts
  feature/card/build.gradle.kts
  feature/deck/build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 2️⃣ Priortiy: Medium, ✨ Type: Feature

#10 🔀 :: (#9) implement designsystem module
  core/designsystem/.gitignore
  core/designsystem/build.gradle.kts
  core/designsystem/consumer-rules.pro
  core/designsystem/proguard-rules.pro
  core/designsystem/src/androidTest/java/com/example/designsystem/ExampleInstrumentedTest.kt
  core/designsystem/src/main/AndroidManifest.xml
  core/designsystem/src/test/java/com/example/designsystem/ExampleUnitTest.kt
  settings.gradle.kts
Labels: 3️⃣ Priority: Low, ✨ Type: Feature

#12 🔀 :: (#11) implement designsystem typography and color
  core/designsystem/src/main/java/com/example/designsystem/theme/Color.kt
  core/designsystem/src/main/java/com/example/designsystem/theme/Theme.kt
  core/designsystem/src/main/java/com/example/designsystem/theme/Typography.kt
  core/designsystem/src/main/res/font/cookierun_black.otf
  core/designsystem/src/main/res/font/cookierun_bold.otf
  core/designsystem/src/main/res/font/cookierun_regular.otf
Labels: 3️⃣ Priority: Low, 🎨 Type: Publishing

#14 🔀 :: (#13) implement design system icon
  core/designsystem/src/main/java/com/example/designsystem/icon/Icon.kt
  core/designsystem/src/main/res/drawable/ic_checkmark.xml
  core/designsystem/src/main/res/drawable/ic_chevron_double_down.xml
  core/designsystem/src/main/res/drawable/ic_chevron_double_left.xml
  core/designsystem/src/main/res/drawable/ic_chevron_double_right.xml
  core/designsystem/src/main/res/drawable/ic_chevron_double_up.xml
  core/designsystem/src/main/res/drawable/ic_chevron_down.xml
  core/designsystem/src/main/res/drawable/ic_chevron_left.xml
  core/designsystem/src/main/res/drawable/ic_chevron_right.xml
  core/designsystem/src/main/res/drawable/ic_chevron_up.xml
  core/designsystem/src/main/res/drawable/ic_copy.xml
  core/designsystem/src/main/res/drawable/ic_cross.xml
  core/designsystem/src/main/res/drawable/ic_filter.xml
  core/designsystem/src/main/res/drawable/ic_garbage.xml
  core/designsystem/src/main/res/drawable/ic_horizon_ellipsis.xml
  core/designsystem/src/main/res/drawable/ic_link.xml
  core/designsystem/src/main/res/drawable/ic_minus.xml
  core/designsystem/src/main/res/drawable/ic_pencil.xml
  core/designsystem/src/main/res/drawable/ic_plus.xml
  core/designsystem/src/main/res/drawable/ic_search.xml
  core/designsystem/src/main/res/drawable/ic_vertical_ellipsis.xml
Labels: 3️⃣ Priority: Low, 🎨 Type: Publishing

#16 🔀 :: (#15) implement design system button component
  core/designsystem/src/main/java/com/example/designsystem/component/button/ButtonType.kt
  core/designsystem/src/main/java/com/example/designsystem/component/button/CookieboxButton.kt
  core/designsystem/src/main/java/com/example/designsystem/theme/Color.kt
  core/designsystem/src/main/java/com/example/designsystem/theme/Theme.kt
Labels: 3️⃣ Priority: Low, 🎨 Type: Publishing

#18 🔀 :: (#17) implement design system textfield component
  core/designsystem/src/main/java/com/example/designsystem/component/textfield/CookieboxTextField.kt
Labels: 3️⃣ Priority: Low, ✨ Type: Feature

#20 🔀 :: (#19) add modifier to icon
  core/designsystem/src/main/java/com/example/designsystem/icon/Icon.kt
Labels: 3️⃣ Priority: Low, ⚡Type: Simple

#22 🔀 :: (#21) implement design system chip component
  core/designsystem/src/main/java/com/example/designsystem/component/chip/ChipType.kt
  core/designsystem/src/main/java/com/example/designsystem/component/chip/CookieboxChip.kt
  core/designsystem/src/main/java/com/example/designsystem/theme/Color.kt
  core/designsystem/src/main/java/com/example/designsystem/theme/Theme.kt
Labels: 3️⃣ Priority: Low, ✨ Type: Feature

#26 🔀 :: (#25) implement design system segmented button component
  core/designsystem/src/main/java/com/example/designsystem/component/button/CookieboxButton.kt
  core/designsystem/src/main/java/com/example/designsystem/component/button/CookieboxSegmentedButton.kt
  core/designsystem/src/main/java/com/example/designsystem/theme/Theme.kt
Labels: 3️⃣ Priority: Low, ✨ Type: Feature

#28 🔀 :: (#23) implement design system dialog component
  build-logic/src/main/java/cookiebox.android.compose.gradle.kts
  core/designsystem/src/main/java/com/example/designsystem/component/dialog/CookieboxDialog.kt
Labels: 3️⃣ Priority: Low, 🎨 Type: Publishing

#30 🔀 :: (#29) implement design system snackbar component
  core/designsystem/src/main/java/com/example/designsystem/component/snackbar/CookieboxSnackbar.kt
Labels: 3️⃣ Priority: Low, 🎨 Type: Publishing

#32 🔀 :: (#31) implement design system deck item component
  core/designsystem/src/main/java/com/example/designsystem/component/deck_item/CookieboxDeckItem.kt
  core/designsystem/src/main/java/com/example/designsystem/component/deck_item/DeckItemType.kt
  core/designsystem/src/main/java/com/example/designsystem/component/dialog/CookieboxDialog.kt
  core/designsystem/src/main/java/com/example/designsystem/theme/Color.kt
  core/designsystem/src/main/java/com/example/designsystem/theme/Theme.kt
Labels: 3️⃣ Priority: Low, 🎨 Type: Publishing

#34 🔀 :: (#27) implement design system menu component
  core/designsystem/src/main/java/com/example/designsystem/component/menu/CookieboxMenu.kt
  core/designsystem/src/main/java/com/example/designsystem/component/menu/CookieboxMenuBox.kt
Labels: 3️⃣ Priority: Low, ✨ Type: Feature

#35 🔀 :: (#31) implement design system deck item component
  core/designsystem/src/main/java/com/example/designsystem/component/bottom_sheet/CookieboxDeckBottomSheet.kt
  core/designsystem/src/main/java/com/example/designsystem/theme/Color.kt
  core/designsystem/src/main/java/com/example/designsystem/theme/Theme.kt
Labels: 3️⃣ Priority: Low, 🎨 Type: Publishing

#37 🔀 :: (#36) implement design system filter dialog component
  build-logic/src/main/java/cookiebox.android.compose.gradle.kts
  core/designsystem/src/main/java/com/example/designsystem/component/button/CookieboxButton.kt
  core/designsystem/src/main/java/com/example/designsystem/component/button/CookieboxSegmentedButton.kt
  core/designsystem/src/main/java/com/example/designsystem/component/dialog/CookieboxFilterDialog.kt
  core/designsystem/src/main/java/com/example/designsystem/component/menu/CookieboxMenu.kt
  core/designsystem/src/main/java/com/example/designsystem/component/menu/CookieboxMenuBox.kt
Labels: 3️⃣ Priority: Low, ✨ Type: Feature

#39 🔀 :: (#38) implement design system card item component
  core/designsystem/src/main/java/com/example/designsystem/component/card_item/CookieboxCardItem.kt
  core/designsystem/src/main/java/com/example/designsystem/theme/Color.kt
  core/designsystem/src/main/java/com/example/designsystem/theme/Theme.kt
  core/designsystem/src/main/res/drawable-hdpi/ic_cookie.webp
  core/designsystem/src/main/res/drawable-mdpi/ic_cookie.webp
  core/designsystem/src/main/res/drawable-xhdpi/ic_cookie.webp
  core/designsystem/src/main/res/drawable-xxhdpi/ic_cookie.webp
  core/designsystem/src/main/res/drawable-xxxhdpi/ic_cookie.webp
Labels: 3️⃣ Priority: Low, ✨ Type: Feature

#41 🔀 :: (#40) design system access restriction
  core/designsystem/src/main/java/com/example/designsystem/component/bottom_sheet/CookieboxDeckBottomSheet.kt
  core/designsystem/src/main/java/com/example/designsystem/component/button/CookieboxButton.kt
  core/designsystem/src/main/java/com/example/designsystem/component/button/CookieboxSegmentedButton.kt
  core/designsystem/src/main/java/com/example/designsystem/component/card_item/CookieboxCardItem.kt
  core/designsystem/src/main/java/com/example/designsystem/component/chip/CookieboxChip.kt
  core/designsystem/src/main/java/com/example/designsystem/component/deck_item/CookieboxDeckItem.kt
  core/designsystem/src/main/java/com/example/designsystem/component/dialog/CookieboxDialog.kt
  core/designsystem/src/main/java/com/example/designsystem/component/dialog/CookieboxFilterDialog.kt
  core/designsystem/src/main/java/com/example/designsystem/component/menu/CookieboxMenu.kt
  core/designsystem/src/main/java/com/example/designsystem/component/menu/CookieboxMenuBox.kt
  core/designsystem/src/main/java/com/example/designsystem/component/snackbar/CookieboxSnackbar.kt
  core/designsystem/src/main/java/com/example/designsystem/component/textfield/CookieboxTextField.kt
Labels: 3️⃣ Priority: Low, ✨ Type: Feature

#43 🔀 :: (#42) implement no ripple clickable extension
  core/designsystem/src/main/java/com/example/designsystem/component/card_item/CookieboxCardItem.kt
  core/designsystem/src/main/java/com/example/designsystem/component/deck_item/CookieboxDeckItem.kt
  core/designsystem/src/main/java/com/example/designsystem/component/dialog/CookieboxDialog.kt
  core/designsystem/src/main/java/com/example/designsystem/component/dialog/CookieboxFilterDialog.kt
  core/designsystem/src/main/java/com/example/designsystem/component/modifier/CookieboxClickable.kt
Labels: 3️⃣ Priority: Low, 🪛 Type: Performance

#45 🔀 :: (#44) modify cookiebox chip component color
  core/designsystem/src/main/java/com/example/designsystem/component/chip/CookieboxChip.kt
  core/designsystem/src/main/java/com/example/designsystem/theme/Color.kt
  core/designsystem/src/main/java/com/example/designsystem/theme/Theme.kt
Labels: ✨ Type: Feature, 🎨 Type: Publishing
