Repository cookierun-tcg-service-developer/CookieBox-Android, pull requests merged in 2024-01, with the labels that each got.

#53 🔀 :: (#52) write navigation logic
  app/build.gradle.kts
  app/src/main/java/com/example/cookiebox/.gitkeep
  app/src/main/java/com/example/cookiebox/CookieBoxNavHost.kt
  app/src/main/java/com/example/cookiebox/MainActivity.kt
  build-logic/src/main/java/cookiebox.android.application.gradle.kts
  build-logic/src/main/java/cookiebox.android.feature.gradle.kts
  core/navigation/.gitignore
  core/navigation/build.gradle.kts
  core/navigation/consumer-rules.pro
  core/navigation/proguard-rules.pro
  core/navigation/src/androidTest/java/com/example/navigation/ExampleInstrumentedTest.kt
  core/navigation/src/main/AndroidManifest.xml
  core/navigation/src/test/java/com/example/navigation/ExampleUnitTest.kt
  feature/card/src/main/java/com/example/card/CardNavigation.kt
  feature/card/src/main/java/com/example/card/CardScreen.kt
  feature/deck/src/main/java/com/example/deck/DeckDetailNavigation.kt
  feature/deck/src/main/java/com/example/deck/DeckDetailScreen.kt
  feature/deck/src/main/java/com/example/deck/DeckListNavigation.kt
  feature/deck/src/main/java/com/example/deck/DeckListScreen.kt
  settings.gradle.kts
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#55 🔀 :: (#54) migrate kapt to ksp
  build-logic/src/main/java/com/example/cookiebox/HiltAndroid.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: 3️⃣ Priority: Low, 🪛 Type: Performance

#57 🔀 :: (#56) migrate gson to moshi
  core/data/build.gradle.kts
  gradle/libs.versions.toml
Labels: 3️⃣ Priority: Low, 🪛 Type: Performance

#59 🔀 :: (#58) setting for di
  .github/workflows/android.yml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/cookiebox/CookieBoxApplication.kt
  app/src/main/java/com/example/cookiebox/modules/NetworkModule.kt
Labels: 3️⃣ Priority: Low, ⚙ Type: Setting

#61 🔀 :: (#60) add compose compiler version to version catalog
  build-logic/src/main/java/com/example/cookiebox/ComposeAndroid.kt
  gradle/libs.versions.toml
Labels: 3️⃣ Priority: Low, ⚡Type: Simple

#63 🔀 :: (#62) fix delete selection button
  feature/deck/src/main/java/com/example/deck/DeckListScreen.kt
Labels: 3️⃣ Priority: Low, 🐞 Type: Bug
